anchor_navigation = false
host = "127.0.0.1"
max_upload_size_mb = 440
port = 8080
private_paths = ["home"]
protected_paths = ["home", "home/*"]
public_access = false
upload_directory = "app_flask/uploads"
